imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    #- { resource: "@BackendAdminBundle/Resources/config/services.yml" }


# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app_locales: [es, en]
    avatars_directory: '%kernel.root_dir%/../web/uploads/images/avatars/'
    complex_avatars_directory: '%kernel.root_dir%/../web/uploads/images/complex/'
    polls_directory: '%kernel.root_dir%/../web/uploads/images/poll_questions/'
    uploads_directory: '%kernel.root_dir%/../web/uploads/images/'
    ios_cert:       '%kernel.project_dir%/app/config/ios/pushdev.pem' # required for ios push notifications
    mailer_port: 587

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    #form:            ~
    form: { enabled: true }
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    serializer:
        enabled: true
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    #trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        locales: "%app_locales%"
        # ...

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset: UTF8
        mapping_types:
            enum:       string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:  "%mailer_port%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Backend\AdminBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    ## To solve the problem
    from_email:
        address: "noreply@bettercondos.com"
        sender_name: "No Reply"
    #registration:
    #    form:
    #        type: Backend\MyFOSUserBundle\Form\Type\RegistrationFormType
    #    confirmation:
    #        from_email:
    #            address:        info@bettercondos.com
    #            sender_name:    Registro BetterCondos
    #        enabled:    true
    #        #template: WbcAdministratorBundle:Default:confirmed.html.twig
    resetting:
        token_ttl: 0    # no restrictions on resetting password
        email:
            template:   '@BackendMyFOSUser/Resetting/email.txt.twig'
            from_email:
                address: info@bettercondos.com
                sender_name: BetterCondos

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json


lexik_translation:
    fallback_locale: [en]         # (required) default locale(s) to use
    managed_locales: [en, es] # (required) locales that the bundle has to manage
    exporter:
        use_yml_tree: true
    dev_tools:
        enable: false
        create_missing: false
        file_format: yml

lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/app/config/jwt/private.pem' # required for token creation
    public_key:       '%kernel.project_dir%/app/config/jwt/public.pem'  # required for token verification
    pass_phrase:      'pizotesoft' # required for token creation, usage of an environment variable is recommended
    token_ttl:        3600

nelmio_api_doc:
    documentation:
        info:
            title: BetterCondos API
            description: Este es el RESTful API de BetterCondos
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Authorization: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []

    routes: # to filter documented routes
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

    #models: { use_jms: false }


vresh_twilio:
    #(Required) Your Account SID from www.twilio.com/user/account
    sid: 'AC5e0560fd1cd9064b767fe5c046242ece'
    #(Required) Your Auth Token from www.twilio.com/user/account
    authToken: '3242fdcf4db8814039d6b756b06100a0'
    #(Optional, default: '2010-04-01') Twilio API version
    version: '2019-04-01'
    #(Optional, default: 1) Number of times to retry failed requests
    retryAttempts: 3


nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
            hosts: ['^api\.']


#notifications:
#    app_id:     780232
#    app_key:    d1cbbf9a5800bd8ec6fe
#    app_secret: 656088be909f90068075
#    cluster:    us2
    # Optional
    # Default false: work without ssl encryption
    # Set it to true to work with ssl encryption
#    encrypted:  false