Backend\AdminBundle\Entity\CommonAreaType:
    type: entity
    table: common_area_type
    repositoryClass: Backend\AdminBundle\Repository\CommonAreaTypeRepository
    indexes:
        complex_id:
            columns:
                - complex_id
        created_by:
            columns:
                - created_by
        updated_by:
            columns:
                - updated_by
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                default: ''
            column: name
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: description
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
    manyToOne:
        complex:
            targetEntity: Complex
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                complex_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
