Backend\AdminBundle\Entity\CommonAreaReservation:
    type: entity
    table: common_area_reservation
    repositoryClass: Backend\AdminBundle\Repository\CommonAreaReservationRepository
    indexes:
        common_area_reservation_status_id:
            columns:
                - common_area_reservation_status_id
        created_by:
            columns:
                - created_by
        common_area_id:
            columns:
                - common_area_id
        reserved_by:
            columns:
                - reserved_by
        updated_by:
            columns:
                - updated_by
        property_id:
            columns:
                - property_id
        tenant_contract_id:
            columns:
                - tenant_contract_id


    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        approved:
            type: datetime
            nullable: true
            column: approved

        reservationDateFrom:
            type: datetime
            nullable: false
            column: reservation_date_from
        reservationDateTo:
            type: datetime
            nullable: false
            column: reservation_date_to
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
    manyToOne:
        tenantContract:
            targetEntity: TenantContract
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tenant_contract_id:
                    referencedColumnName: id
            orphanRemoval: false
        commonArea:
            targetEntity: CommonArea
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                common_area_id:
                    referencedColumnName: id
            orphanRemoval: false
        property:
            targetEntity: Property
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                property_id:
                    referencedColumnName: id
            orphanRemoval: false


        commonAreaReservationStatus:
            targetEntity: CommonAreaReservationStatus
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                common_area_reservation_status_id:
                    referencedColumnName: id
            orphanRemoval: false
        reservedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                reserved_by:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
