Backend\AdminBundle\Entity\ComplexFaq:
    type: entity
    table: complex_faq
    repositoryClass: Backend\AdminBundle\Repository\ComplexFaqRepository
    indexes:
        complex_id:
            columns:
                - complex_id
        updated_by:
            columns:
                - updated_by
        created_by:
            columns:
                - created_by
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        orderList:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: order_list
        question:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: question
        answer:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: answer
        enabled:
            type: boolean
            nullable: false
            options:
                default: '1'
        createdAt:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: updated_at
    manyToOne:
        complex:
            targetEntity: Complex
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                complex_id:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
