Backend\AdminBundle\Entity\ComplexFaq:
    type: entity
    table: complex_faq
    repositoryClass: Backend\AdminBundle\Repository\ComplexFaqRepository
    indexes:
        complex_id:
            columns:
                - complex_id
        updated_by:
            columns:
                - updated_by
        created_by:
            columns:
                - created_by
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descriptionES:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: description_es
        descriptionEN:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: description_en
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at

        enabled:
            type: boolean
            nullable: false
            options:
                default: true
    manyToOne:

        complex:
            targetEntity: Complex
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                complex_id:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
