Backend\AdminBundle\Entity\GeoCountry:
    type: entity
    table: geo_country
    repositoryClass: Backend\AdminBundle\Repository\GeoCountryRepository
    indexes:
        updated_by:
            columns:
                - updated_by
        created_by:
            columns:
                - created_by
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                default: ''
        shortName:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
                default: ''
        locale:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
                default: 'en'

        code:
            type: string
            nullable: true
            length: 8
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        enabled:
            type: boolean
            nullable: false
            options:
                default: '1'

    manyToOne:
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
