Backend\AdminBundle\Entity\GeoState:
    type: entity
    table: geo_state
    repositoryClass: Backend\AdminBundle\Repository\GeoStateRepository
    indexes:
        created_by:
            columns:
                - created_by
        geo_country_id:
            columns:
                - geo_country_id
        updated_by:
            columns:
                - updated_by
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                default: ''
        zipCode:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
                default: ''
            column: zip_code
        timezoneOffset:
            type: string
            nullable: true
            length: 16
            options:
                fixed: false
            column: timezone_offset
        timezoneName:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
            column: timezone_name
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
    manyToOne:
        geoCountry:
            targetEntity: GeoCountry
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                geo_country_id:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
