Backend\AdminBundle\Entity\PaymentLog:
    type: entity
    table: payment_log
    repositoryClass: Backend\AdminBundle\Repository\PaymentLogRepository
    indexes:
        property_contract_transaction_id:
            columns:
                - property_contract_transaction_id
        updated_by:
            columns:
                - updated_by
        created_by:
            columns:
                - created_by
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        status:
            type: string
            nullable: true
            length: 16
            options:
                fixed: false
        paymentAmount:
            type: float
            nullable: false
            precision: 10
            scale: 2
            options:
                default: 0.00
            column: payment_amount

        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    manyToOne:
        propertyContractTransaction:
            targetEntity: PropertyContractTransaction
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                property_contract_transaction_id:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
