Backend\AdminBundle\Entity\PollQuestionOption:
    type: entity
    table: poll_question_option
    repositoryClass: Backend\AdminBundle\Repository\PollQuestionOptionRepository
    indexes:
        created_by:
            columns:
                - created_by
        poll_question_id:
            columns:
                - poll_question_id
        updated_by:
            columns:
                - updated_by
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        questionOption:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
                comment: 'opcion a elegir'
            column: question_option
        pollFilePhoto:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: poll_file_photo
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
    manyToOne:
        pollQuestion:
            targetEntity: PollQuestion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                poll_question_id:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
