Backend\AdminBundle\Entity\PropertyType:
    type: entity
    table: property_type
    repositoryClass: Backend\AdminBundle\Repository\PropertyTypeRepository
    indexes:
        updated_by:
            columns:
                - updated_by
        created_by:
            columns:
                - created_by
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nameES:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                default: ''
            column: name_es
        nameEN:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                default: ''
            column: name_en
        descriptionES:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: description_es
        descriptionEN:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: description_en
        createdAt:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: updated_at
        enabled:
            type: boolean
            nullable: false
            options:
                default: '1'
    manyToOne:
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
