Backend\AdminBundle\Entity\ShiftUserComplex:
    type: entity
    table: shift_user_complex
    repositoryClass: Backend\AdminBundle\Repository\ShiftUserConmplexRepository
    indexes:
        shift_id:
            columns:
                - shift_id
        updated_by:
            columns:
                - updated_by
        user_complex_id:
            columns:
                - user_complex_id
        created_by:
            columns:
                - created_by
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: updated_at
        enabled:
            type: boolean
            nullable: false
            options:
                default: '1'
    manyToOne:
        userComplex:
            targetEntity: UserComplex
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_complex_id:
                    referencedColumnName: id
            orphanRemoval: false
        shift:
            targetEntity: Shift
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                shift_id:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
