Backend\AdminBundle\Entity\Shift:
    type: entity
    table: shift
    repositoryClass: Backend\AdminBundle\Repository\ShiftRepository
    indexes:
        updated_by:
            columns:
                - updated_by
        created_by:
            columns:
                - created_by
        assigned_to:
            columns:
                - assigned_to

        complex_id:
            columns:
                - complex_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        weekdaySingle:
            type: integer
            nullable: true
            options:
                unsigned: false
                comment: '1 es lunes y 7 es domingo'
            column: weekday_single
        hourFrom:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
                default: ''
            column: hour_from
        hourTo:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
                default: ''
            column: hour_to

        overtime:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        flexibleHours:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: flexible_hours
        flexitour:
            type: integer
            nullable: true
            options:
                unsigned: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
    manyToOne:
        assignedTo:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                assigned_to:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
        complex:
            targetEntity: Complex
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                complex_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
