Backend\AdminBundle\Entity\TenantContract:
    type: entity
    table: tenant_contract
    repositoryClass: Backend\AdminBundle\Repository\TenantContractRepository
    indexes:
        property_contract_id:
            columns:
                - property_contract_id
        created_by:
            columns:
                - created_by
        user_id:
            columns:
                - user_id
        role_id:
            columns:
                - role_id
        updated_by:
            columns:
                - updated_by
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        rating:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        createdAt:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: updated_at
        isOwner:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: is_owner
        enabled:
            type: boolean
            nullable: false
            options:
                default: '1'
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        propertyContract:
            targetEntity: PropertyContract
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                property_contract_id:
                    referencedColumnName: id
            orphanRemoval: false
        role:
            targetEntity: Role
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                role_id:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
