Backend\AdminBundle\Entity\TenantContract:
    type: entity
    table: tenant_contract
    repositoryClass: Backend\AdminBundle\Repository\TenantContractRepository
    indexes:
        property_contract_id:
            columns:
                - property_contract_id
        created_by:
            columns:
                - created_by
        user_id:
            columns:
                - user_id
        updated_by:
            columns:
                - updated_by
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        playerId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: player_id
        propertyCode:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
            column: property_code
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
        invitationAccepted:
            type: boolean
            nullable: false
            options:
                default: false
        invitationUserEmail:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
        ownerEmail:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
        mainTenant:
            type: boolean
            nullable: false
            options:
                default: false
            column: main_tenant

    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        propertyContract:
            targetEntity: PropertyContract
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                property_contract_id:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
