Backend\AdminBundle\Entity\TicketCategory:
    type: entity
    table: ticket_category
    repositoryClass: Backend\AdminBundle\Repository\TicketCategoryRepository
    indexes:
        updated_by:
            columns:
                - updated_by
        created_by:
            columns:
                - created_by
        complex_id:
            columns:
                - complex_id

        icon_id:
            columns:
                - icon_id

    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                default: ''
            column: name
        color:
            type: string
            nullable: false
            length: 7
            options:
                fixed: false
                default: ''
            column: color
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: description
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        isGeneral:
            type: boolean
            nullable: false
            options:
                default: false
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
    manyToOne:
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
        complex:
            targetEntity: Complex
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                complex_id:
                    referencedColumnName: id
            orphanRemoval: false
        icon:
            targetEntity: Icon
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                icon_id:
                    referencedColumnName: id
            orphanRemoval: false


    lifecycleCallbacks: {  }
