Backend\AdminBundle\Entity\TicketFilePhoto:
    type: entity
    table: ticket_file_photo
    repositoryClass: Backend\AdminBundle\Repository\TicketFilePhotoRepository
    indexes:
        updated_by:
            columns:
                - updated_by
        created_by:
            columns:
                - created_by
        ticket_comment_id:
            columns:
                - ticket_comment_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: updated_at
        enabled:
            type: boolean
            nullable: false
            options:
                default: '1'
    manyToOne:
        ticketComment:
            targetEntity: TicketComment
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ticket_comment_id:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
