Backend\AdminBundle\Entity\TicketStatus:
    type: entity
    table: ticket_status
    repositoryClass: Backend\AdminBundle\Repository\TicketStatusRepository
    indexes:
        updated_by:
            columns:
                - updated_by
        created_by:
            columns:
                - created_by

    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nameES:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                default: ''
            column: name_es
        nameEN:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                default: ''
            column: name_en
        isPublic:
            type: boolean
            nullable: false
            options:
                default: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
    manyToOne:
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
