Backend\AdminBundle\Entity\TicketChangeLog:
    type: entity
    table: ticket_change_log
    repositoryClass: Backend\AdminBundle\Repository\TicketChangeLogRepository
    indexes:
        updated_by:
            columns:
                - updated_by
        created_by:
            columns:
                - created_by
        ticket_id:
            columns:
                - ticket_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        action:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
                comment: 'indica que tipo de acci贸n ejecut贸 DELETE, UPDATE, CREATE, OTHER'
                default: ''
        description:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
                comment: 'Descripci贸n de la acci贸n'
                default: ''
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    manyToOne:
        ticket:
            targetEntity: Ticket
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ticket_id:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
