Backend\AdminBundle\Entity\TicketStatusLog:
    type: entity
    table: ticket_status_log
    repositoryClass: Backend\AdminBundle\Repository\TicketStatusLogRepository
    indexes:
        ticket_status_id:
            columns:
                - ticket_status_id
        ticket_id:
            columns:
                - ticket_id
        updated_by:
            columns:
                - updated_by
        created_by:
            columns:
                - created_by
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    manyToOne:
        ticket:
            targetEntity: Ticket
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ticket_id:
                    referencedColumnName: id
            orphanRemoval: false
        ticketStatus:
            targetEntity: TicketStatus
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ticket_status_id:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
