Backend\AdminBundle\Entity\UserNotification:
    type: entity
    table: user_notification
    repositoryClass: Backend\AdminBundle\Repository\UserNotificationRepository
    indexes:
        notification_type_id:
            columns:
                - notification_type_id
        updated_by:
            columns:
                - updated_by
        sent_to:
            columns:
                - sent_to
        complex_to_notify:
            columns:
                - complex_to_notify
        sector_to_notify:
            columns: sector_to_notify

        property_to_notify:
            columns: property_to_notify

        created_by:
            columns:
                - created_by
        ticket_id:
            columns:
                - ticket_id
        ticket_category_id:
            columns:
                - ticket_category_id

        tenant_contract_id:
            columns:
                - tenant_contract_id
        common_area_reservation_id:
            columns:
                - common_area_reservation_id

    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        isRead:
            type: boolean
            nullable: false
            options:
                default: false
        title:
            type: text
            nullable: true
            length: 160
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false

        notice:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        reminder:
            type: integer
            nullable: true
            options:
                unsigned: false
                comment: '1 to 24hrs'
            column: reminder

        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at

        isScheduled:
            type: boolean
            nullable: false
            options:
                default: false
        scheduledTime:
            type: datetime
            nullable: true
            column: scheduled_time

        enabled:
            type: boolean
            nullable: false
            options:
                default: true
    manyToOne:
        sentTo:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sent_to:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
        notificationType:
            targetEntity: NotificationType
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                notification_type_id:
                    referencedColumnName: id
            orphanRemoval: false
        ticket:
            targetEntity: Ticket
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ticket_id:
                    referencedColumnName: id
            orphanRemoval: false
        commonAreaReservation:
            targetEntity: CommonAreaReservation
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                common_area_reservation_id:
                    referencedColumnName: id
            orphanRemoval: false
        tenantContract:
            targetEntity: TenantContract
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tenant_contract_id:
                    referencedColumnName: id
            orphanRemoval: false

        complexToNotify:
            targetEntity: Complex
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                complex_to_notify:
                    referencedColumnName: id
            orphanRemoval: false

        sectorToNotify:
            targetEntity: ComplexSector
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sector_to_notify:
                    referencedColumnName: id
            orphanRemoval: false

        propertyToNotify:
            targetEntity: Property
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                property_to_notify:
                    referencedColumnName: id
            orphanRemoval: false

        ticketCategory:
            targetEntity: TicketCategory
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ticket_category_id:
                    referencedColumnName: id

    lifecycleCallbacks: {  }
