backend_admin_agreement_plan_index:
    path: /
    defaults:
        _controller: BackendAdminBundle:AgreementPlan:index

agreement_plan_list_datatables:
    path: /agreementPlan/list/datatables
    defaults:
        _controller: BackendAdminBundle:AgreementPlan:listDatatables

backend_admin_agreement_plan_new:
    path:     /new/
    defaults: { _controller: "BackendAdminBundle:AgreementPlan:new" }
    #methods:  [GET, POST]

backend_admin_agreement_plan_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendAdminBundle:AgreementPlan:edit" }

backend_admin_agreement_plan_create:
    path:     /create
    defaults: { _controller: "BackendAdminBundle:AgreementPlan:create" }
    methods:  POST

backend_admin_agreement_plan_update:
    path:     /{id}/update
    defaults: { _controller: "BackendAdminBundle:AgreementPlan:update" }
    methods:  POST

backend_admin_agreement_plan_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendAdminBundle:AgreementPlan:delete" }

    #methods:  DELETE
