backend_admin_common_area_reservation_index:
    path: /
    defaults:
        _controller: BackendAdminBundle:CommonAreaReservation:index

common_area_reservation_list_datatables:
    path: /commonAreaReservation/list/datatables
    defaults:
        _controller: BackendAdminBundle:CommonAreaReservation:listDatatables

backend_admin_common_area_reservation_approve:
    path: /{id}/commonAreaReservationApprove
    defaults:
        _controller: BackendAdminBundle:CommonAreaReservation:approve


backend_admin_common_area_reservation_deny:
    path: /{id}/commonAreaReservationDeny
    defaults:
        _controller: BackendAdminBundle:CommonAreaReservation:deny

backend_admin_common_area_reservation_calendar:
    path: /commonAreaReservationCalendar
    defaults:
        _controller: BackendAdminBundle:CommonAreaReservation:calendar
        
backend_admin_common_area_reservation_new:
    path:     /new/
    defaults: { _controller: "BackendAdminBundle:CommonAreaReservation:new" }
    #methods:  [GET, POST]

backend_admin_common_area_reservation_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendAdminBundle:CommonAreaReservation:edit" }

backend_admin_common_area_reservation_create:
    path:     /create
    defaults: { _controller: "BackendAdminBundle:CommonAreaReservation:create" }
    methods:  POST

backend_admin_common_area_reservation_update:
    path:     /{id}/update
    defaults: { _controller: "BackendAdminBundle:CommonAreaReservation:update" }
    methods:  POST

backend_admin_common_area_reservation_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendAdminBundle:CommonAreaReservation:delete" }


backend_admin_common_area_reservation_availability:
    path:     /getAvailability
    defaults: { _controller: "BackendAdminBundle:CommonAreaReservation:getAvailability" }


backend_admin_common_area_reservation_get_cost:
    path:     /getCost
    defaults: { _controller: "BackendAdminBundle:CommonAreaReservation:getCost" }


backend_admin_common_area_reservation_update_payment:
    path:     /updatePayment
    defaults: { _controller: "BackendAdminBundle:CommonAreaReservation:updatePayment" }

common_area_reservation_list_log:
    path: /{reservation}/commonAreaReservation/list/log
    defaults:
        _controller: BackendAdminBundle:CommonAreaReservation:listLog

backend_admin_common_area_reservation_comment:
    path: /{id}/commonAreaReservation/comment
    defaults:
        _controller: BackendAdminBundle:CommonAreaReservation:comment
