backend_admin_common_area_reservation_status_index:
    path: /
    defaults:
        _controller: BackendAdminBundle:CommonAreaReservationStatus:index

common_area_reservation_status_list_datatables:
    path: /commonAreaReservationStatus/list/datatables
    defaults:
        _controller: BackendAdminBundle:CommonAreaReservationStatus:listDatatables

backend_admin_common_area_reservation_status_new:
    path:     /new/
    defaults: { _controller: "BackendAdminBundle:CommonAreaReservationStatus:new" }
    #methods:  [GET, POST]

backend_admin_common_area_reservation_status_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendAdminBundle:CommonAreaReservationStatus:edit" }

backend_admin_common_area_reservation_status_create:
    path:     /create
    defaults: { _controller: "BackendAdminBundle:CommonAreaReservationStatus:create" }
    methods:  POST

backend_admin_common_area_reservation_status_update:
    path:     /{id}/update
    defaults: { _controller: "BackendAdminBundle:CommonAreaReservationStatus:update" }
    methods:  POST

backend_admin_common_area_reservation_status_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendAdminBundle:CommonAreaReservationStatus:delete" }
    #methods:  DELETE
