backend_admin_common_area_type_index:
    path: /
    defaults:
        _controller: BackendAdminBundle:CommonAreaType:index

common_area_type_list_datatables:
    path: /commonAreaType/list/datatables
    defaults:
        _controller: BackendAdminBundle:CommonAreaType:listDatatables

backend_admin_common_area_type_new:
    path:     /new/
    defaults: { _controller: "BackendAdminBundle:CommonAreaType:new" }
    #methods:  [GET, POST]

backend_admin_common_area_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendAdminBundle:CommonAreaType:edit" }

backend_admin_common_area_type_create:
    path:     /create
    defaults: { _controller: "BackendAdminBundle:CommonAreaType:create" }
    methods:  POST

backend_admin_common_area_type_update:
    path:     /{id}/update
    defaults: { _controller: "BackendAdminBundle:CommonAreaType:update" }
    methods:  POST

backend_admin_common_area_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendAdminBundle:CommonAreaType:delete" }
    #methods:  DELETE
