backend_admin_complex_index:
    path: /
    defaults:
        _controller: BackendAdminBundle:Complex:index

complex_list_datatables:
    path: /complex/list/datatables
    defaults:
        _controller: BackendAdminBundle:Complex:listDatatables

backend_admin_complex_new:
    path:     /new/
    defaults: { _controller: "BackendAdminBundle:Complex:new" }
    #methods:  [GET, POST]

backend_admin_complex_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendAdminBundle:Complex:edit" }

backend_admin_complex_create:
    path:     /create
    defaults: { _controller: "BackendAdminBundle:Complex:create" }
    methods:  POST

backend_admin_complex_update:
    path:     /{id}/update
    defaults: { _controller: "BackendAdminBundle:Complex:update" }
    methods:  POST

backend_admin_complex_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendAdminBundle:Complex:delete" }

    #methods:  DELETE
