backend_admin_poll_question_type_index:
    path: /
    defaults:
        _controller: BackendAdminBundle:PollQuestionType:index

poll_question_type_list_datatables:
    path: /complexType/list/datatables
    defaults:
        _controller: BackendAdminBundle:PollQuestionType:listDatatables

backend_admin_poll_question_type_new:
    path:     /new/
    defaults: { _controller: "BackendAdminBundle:PollQuestionType:new" }
    #methods:  [GET, POST]

backend_admin_poll_question_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendAdminBundle:PollQuestionType:edit" }

backend_admin_poll_question_type_create:
    path:     /create
    defaults: { _controller: "BackendAdminBundle:PollQuestionType:create" }
    methods:  POST

backend_admin_poll_question_type_update:
    path:     /{id}/update
    defaults: { _controller: "BackendAdminBundle:PollQuestionType:update" }
    methods:  POST

backend_admin_poll_question_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendAdminBundle:PollQuestionType:delete" }

    #methods:  DELETE
