backend_admin_property_index:
    path: /
    defaults:
        _controller: BackendAdminBundle:Property:index

property_list_datatables:
    path: /property/list/datatables
    defaults:
        _controller: BackendAdminBundle:Property:listDatatables

backend_admin_property_new:
    path:     /new/
    defaults: { _controller: "BackendAdminBundle:Property:new" }
    #methods:  [GET, POST]

backend_admin_property_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendAdminBundle:Property:edit" }

backend_admin_property_create:
    path:     /create
    defaults: { _controller: "BackendAdminBundle:Property:create" }
    methods:  POST

backend_admin_property_update:
    path:     /{id}/update
    defaults: { _controller: "BackendAdminBundle:Property:update" }
    methods:  POST

backend_admin_property_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendAdminBundle:Property:delete" }
    #methods:  DELETE

backend_admin_property_info:
    path:     /propertyInfo
    defaults: { _controller: "BackendAdminBundle:Property:info" }
    
property_ajax_snippet_image_send:
    path:     /imagesend
    defaults: { _controller: "BackendAdminBundle:Property:imageSend" }


property_ajax_snippet_image_get:
    path:     /imageget
    defaults: { _controller: "BackendAdminBundle:Property:imageGet" }

property_ajax_snippet_image_remove:
    path:     /imageremove
    defaults: { _controller: "BackendAdminBundle:Property:imageRemove" }
    

backend_admin_property_change_section:
    path:     /changeSection
    defaults: { _controller: "BackendAdminBundle:Property:changeSection" }
    #methods:  POST

backend_admin_property_share_ad:
    path:     /shareAd
    defaults: { _controller: "BackendAdminBundle:Property:shareAd" }

backend_admin_property_delete_ad:
    path:     /deleteAd
    defaults: { _controller: "BackendAdminBundle:Property:deleteAd" }
