backend_admin_property_index:
    path: /
    defaults:
        _controller: BackendAdminBundle:Property:index

property_list_datatables:
    path: /property/list/datatables
    defaults:
        _controller: BackendAdminBundle:Property:listDatatables

backend_admin_property_new:
    path:     /new/
    defaults: { _controller: "BackendAdminBundle:Property:new" }
    #methods:  [GET, POST]

backend_admin_property_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendAdminBundle:Property:edit" }

backend_admin_property_create:
    path:     /create
    defaults: { _controller: "BackendAdminBundle:Property:create" }
    methods:  POST

backend_admin_property_update:
    path:     /{id}/update
    defaults: { _controller: "BackendAdminBundle:Property:update" }
    methods:  POST

backend_admin_property_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendAdminBundle:Property:delete" }
    #methods:  DELETE

backend_admin_property_info:
    path:     /propertyInfo
    defaults: { _controller: "BackendAdminBundle:Property:info" }
    
property_ajax_snippet_image_send:
    path:     /imagesend
    defaults: { _controller: "BackendAdminBundle:Property:imageSend" }


property_ajax_snippet_image_get:
    path:     /imageget
    defaults: { _controller: "BackendAdminBundle:Property:imageGet" }

property_ajax_snippet_image_remove:
    path:     /imageremove
    defaults: { _controller: "BackendAdminBundle:Property:imageRemove" }
    

backend_admin_property_change_section:
    path:     /changeSection
    defaults: { _controller: "BackendAdminBundle:Property:changeSection" }
    #methods:  POST

backend_admin_property_share_ad:
    path:     /shareAd
    defaults: { _controller: "BackendAdminBundle:Property:shareAd" }

backend_admin_property_delete_ad:
    path:     /deleteAd
    defaults: { _controller: "BackendAdminBundle:Property:deleteAd" }

backend_admin_property_new_agreement:
    path:     /newAgreement/
    defaults: { _controller: "BackendAdminBundle:Property:newAgreement" }

backend_admin_property_detail:
    path:     /{id}/detail
    defaults: { _controller: "BackendAdminBundle:Property:detail" }


backend_admin_property_update_maintenance:
    path:     /{id}/updateMaintenance
    defaults: { _controller: "BackendAdminBundle:Property:updateMaintenance" }

backend_admin_property_contract_extend:
    path:     /{propertycontract}/contractextend
    defaults: { _controller: "BackendAdminBundle:Property:contractExtend" }

backend_admin_property_contract_cancel:
    path:     /{propertycontract}/contractcancel
    defaults: { _controller: "BackendAdminBundle:Property:contractCancel" }

property_ticket_list_datatables:
    path: /{property}/propertyticket/list/datatables
    defaults:
        _controller: BackendAdminBundle:Property:listTickets

property_booking_list_datatables:
    path: /{property}/propertybooking/list/datatables
    defaults:
        _controller: BackendAdminBundle:Property:listBookings

property_payment_list_datatables:
    path: /{property}/propertypayment/list/datatables
    defaults:
        _controller: BackendAdminBundle:Property:listPayments

backend_admin_property_invitations:
    path:     /invitations/
    defaults: { _controller: "BackendAdminBundle:Property:invitations" }

backend_admin_property_invitations_import:
    path:     /invitationsimport/
    defaults: { _controller: "BackendAdminBundle:Property:invitationsImport" }


backend_admin_property_invitations_export:
    path:     /invitationsexport/
    defaults: { _controller: "BackendAdminBundle:Property:invitationsExport" }

backend_admin_property_set_post_pubic_ticket:
    path:     /{pcontract}/{value}/postPublicTicket/
    defaults: { _controller: "BackendAdminBundle:Property:postPublicTicket" }

backend_admin_property_generateqrcode:
    path:     /{mycode}/generateqrcode
    defaults: { _controller: "BackendAdminBundle:Property:generateqrcode" }
    #methods:  POST
