backend_admin_property_type_index:
    path: /
    defaults:
        _controller: BackendAdminBundle:PropertyType:index

property_type_list_datatables:
    path: /complexType/list/datatables
    defaults:
        _controller: BackendAdminBundle:PropertyType:listDatatables

backend_admin_property_type_new:
    path:     /new/
    defaults: { _controller: "BackendAdminBundle:PropertyType:new" }
    #methods:  [GET, POST]

backend_admin_property_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendAdminBundle:PropertyType:edit" }

backend_admin_property_type_create:
    path:     /create
    defaults: { _controller: "BackendAdminBundle:PropertyType:create" }
    methods:  POST

backend_admin_property_type_update:
    path:     /{id}/update
    defaults: { _controller: "BackendAdminBundle:PropertyType:update" }
    methods:  POST

backend_admin_property_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendAdminBundle:PropertyType:delete" }

    #methods:  DELETE
