backend_admin_ticket_index:
  path: /
  defaults:
    _controller: BackendAdminBundle:Ticket:index

ticket_list_datatables:
  path: /ticket/list/datatables
  defaults:
    _controller: BackendAdminBundle:Ticket:listDatatables

dashboard_ticket_list_datatables:
  path: /dashboard/ticket/list/datatables
  defaults:
    _controller: BackendAdminBundle:Default:listTickettables


backend_admin_ticket_new:
  path:     /new/
  defaults: { _controller: "BackendAdminBundle:Ticket:new" }
  #methods:  [GET, POST]

backend_admin_ticket_edit:
  path:     /{id}/edit
  defaults: { _controller: "BackendAdminBundle:Ticket:edit" }

backend_admin_ticket_create:
  path:     /create
  defaults: { _controller: "BackendAdminBundle:Ticket:create" }
  methods:  POST

backend_admin_ticket_update:
  path:     /{id}/update
  defaults: { _controller: "BackendAdminBundle:Ticket:update" }
  methods:  POST

backend_admin_ticket_delete:
  path:     /{id}/delete
  defaults: { _controller: "BackendAdminBundle:Ticket:delete" }

  #methods:  DELETE

backend_admin_ticket_close:
  path:     /{id}/close
  defaults: { _controller: "BackendAdminBundle:Ticket:close" }
  methods:  POST

backend_admin_ticket_comment:
  path:     /{id}/comment
  defaults: { _controller: "BackendAdminBundle:Ticket:comment" }
  methods:  POST

backend_admin_ticket_rating_tenant:
  path:     /{id}/ratingtenant
  defaults: { _controller: "BackendAdminBundle:Ticket:ratingTenant" }
  methods:  POST