backend_admin_ticket_index:
  path: /
  defaults:
    _controller: BackendAdminBundle:Ticket:index

ticket_list_datatables:
  path: /ticketType/list/datatables
  defaults:
    _controller: BackendAdminBundle:Ticket:listDatatables

backend_admin_ticket_new:
  path:     /new/
  defaults: { _controller: "BackendAdminBundle:Ticket:new" }
  #methods:  [GET, POST]

backend_admin_ticket_edit:
  path:     /{id}/edit
  defaults: { _controller: "BackendAdminBundle:Ticket:edit" }

backend_admin_ticket_create:
  path:     /create
  defaults: { _controller: "BackendAdminBundle:Ticket:create" }
  methods:  POST

backend_admin_ticket_update:
  path:     /{id}/update
  defaults: { _controller: "BackendAdminBundle:Ticket:update" }
  methods:  POST

backend_admin_ticket_delete:
  path:     /{id}/delete
  defaults: { _controller: "BackendAdminBundle:Ticket:delete" }

  #methods:  DELETE