backend_admin_ticket_type_index:
    path: /
    defaults:
        _controller: BackendAdminBundle:TicketType:index

ticket_type_list_datatables:
    path: /ticketType/list/datatables
    defaults:
        _controller: BackendAdminBundle:TicketType:listDatatables

backend_admin_ticket_type_new:
    path:     /new/
    defaults: { _controller: "BackendAdminBundle:TicketType:new" }
    #methods:  [GET, POST]

backend_admin_ticket_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendAdminBundle:TicketType:edit" }

backend_admin_ticket_type_create:
    path:     /create
    defaults: { _controller: "BackendAdminBundle:TicketType:create" }
    methods:  POST

backend_admin_ticket_type_update:
    path:     /{id}/update
    defaults: { _controller: "BackendAdminBundle:TicketType:update" }
    methods:  POST

backend_admin_ticket_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendAdminBundle:TicketType:delete" }

    #methods:  DELETE
