backend_admin_user_index:
    path: /
    defaults:
        _controller: BackendAdminBundle:User:index

backend_admin_user_show:
    path:     /{id}/show
    defaults: { _controller: "BackendAdminBundle:User:show" }
    methods:  GET

backend_admin_user_new:
    path:     /new
    defaults: { _controller: "BackendAdminBundle:User:new" }
    #methods:  [GET, POST]
    
backend_admin_user_create:
    path:     /create
    defaults: { _controller: "BackendAdminBundle:User:create" }
    requirements: { _method: post }


backend_admin_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendAdminBundle:User:edit" }
    #methods:  [GET, POST]
    

backend_admin_user_update:
    path:     /{id}/update
    defaults: { _controller: "BackendAdminBundle:User:update" }
    requirements: { _method: post|put }     

backend_admin_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendAdminBundle:User:delete" }
    #methods:  DELETE

user_check_existence:
    path:     /usercheckexistence
    defaults: { _controller: "BackendAdminBundle:User:checkExistence" }    
  
    
user_list_datatables:
    path: /user/list/datatables
    defaults:
        _controller: BackendAdminBundle:User:listDatatables

#user_list:
#    path: /user/list
#    defaults:
#        _controller: BackendAdminBundle:User:list
